version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  jenkins:
    driver: ${VOLUMES_DRIVER}

services:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home      
    networks:
      - frontend
      - backend
  nexus:
    container_name: nexus
    build:
      context: ./nexus
    ports:
      - '8081:8081'
    networks:
      - frontend
      - backend      
  sonarqube:
    container_name: sonarqube
    build:
      context: ./sonarqube
    ports:
      - '9000:9000'
    networks:
      - frontend
      - backend         