version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  jenkins:
    driver: ${VOLUMES_DRIVER}

services:
  jenkins:
    container_name: jenkins
    domainname: jenkins.localhost
    hostname: jenkins
    ipc: host
    build:
      context: ./jenkins
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home      
    networks:
      - frontend
      - backend
  nexus:
    container_name: nexus
    domainname: nexus.localhost
    hostname: nexus
    ipc: host    
    build:
      context: ./nexus
    ports:
      - '8081:8081'
    networks:
      - frontend
      - backend      
  sonarqube:
    container_name: sonarqube
    domainname: sonarqube.localhost
    hostname: sonarqube
    ipc: host    
    build:
      context: ./sonarqube
    ports:
      - '9000:9000'
    networks:
      - frontend
      - backend   
  gitlab:
    container_name: gitlab
    domainname: gitlab.localhost
    hostname: gitlab
    ipc: host    
    build:
      context: ./gitlab
    ports:
    - '80:80'
    networks:
      - frontend    
  grafana:
    container_name: grafana
    domainname: grafana.localhost
    hostname: grafana
    ipc: host    
    build:
      context: ./grafana
    ports:
    - '3000:3000'
    networks:
      - frontend          
                 